import { ClassTableData } from "../../models/ClassTableData";

export const artificer: ClassTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Magical Tinkering, Spellcasting",
    infusionsKnown: "-",
    infusedItems: "-",
    cantripsKnown: "3",
    spellSlots: [2, 0, 0, 0, 0],
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Infuse Item",
    infusionsKnown: "4",
    infusedItems: "2",
    cantripsKnown: "3",
    spellSlots: [3, 0, 0, 0, 0],
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Artificer Specialist, The Right Tool for the Job",
    infusionsKnown: "4",
    infusedItems: "2",
    cantripsKnown: "3",
    spellSlots: [4, 2, 0, 0, 0],
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement",
    infusionsKnown: "4",
    infusedItems: "2",
    cantripsKnown: "3",
    spellSlots: [4, 3, 0, 0, 0],
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Artificer Specialist feature",
    infusionsKnown: "4",
    infusedItems: "2",
    cantripsKnown: "4",
    spellSlots: [4, 3, 2, 0, 0],
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Tool Expertise",
    infusionsKnown: "6",
    infusedItems: "3",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 0, 0],
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "Flash of Genius",
    infusionsKnown: "6",
    infusedItems: "3",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 1, 0],
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement",
    infusionsKnown: "6",
    infusedItems: "3",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 2, 0],
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "Artificer Specialist feature",
    infusionsKnown: "6",
    infusedItems: "3",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 1],
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Magic Item Adept",
    infusionsKnown: "8",
    infusedItems: "4",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Spell-Storing Item",
    infusionsKnown: "8",
    infusedItems: "4",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement",
    infusionsKnown: "8",
    infusedItems: "4",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "-",
    infusionsKnown: "8",
    infusedItems: "4",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Magic Item Savant",
    infusionsKnown: "10",
    infusedItems: "5",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Artificer Specialist feature",
    infusionsKnown: "10",
    infusedItems: "5",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement",
    infusionsKnown: "10",
    infusedItems: "5",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "-",
    infusionsKnown: "10",
    infusedItems: "5",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Magic Item Master",
    infusionsKnown: "12",
    infusedItems: "6",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement",
    infusionsKnown: "12",
    infusedItems: "6",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Soul of Artifice",
    infusionsKnown: "12",
    infusedItems: "6",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 2],
  },
];
