import { ClassesTableData } from "../../models/ClassesTable";

export const barbarian: ClassesTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Rage, Unarmored Defense",
    rages: "2",
    rageDamage: "+2",
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Reckless Attack, Danger Sense",
    rages: "2",
    rageDamage: "+2",
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Primal Path, Primal Knowledge (Optional)",
    rages: "3",
    rageDamage: "+2",
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement",
    rages: "3",
    rageDamage: "+2",
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Extra Attack, Fast Movement",
    rages: "3",
    rageDamage: "+2",
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Path feature",
    rages: "4",
    rageDamage: "+2",
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "Feral Instinct, Instinctive Pounce (Optional)",
    rages: "4",
    rageDamage: "+2",
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement",
    rages: "4",
    rageDamage: "+2",
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "Brutal Critical (1 die)",
    rages: "4",
    rageDamage: "+3",
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Path feature, Primal Knowledge (Optional)",
    rages: "4",
    rageDamage: "+3",
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Relentless Rage",
    rages: "4",
    rageDamage: "+3",
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement",
    rages: "5",
    rageDamage: "+3",
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "Brutal Critical (2 dice)",
    rages: "5",
    rageDamage: "+3",
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Path feature",
    rages: "5",
    rageDamage: "+3",
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Persistent Rage",
    rages: "5",
    rageDamage: "+3",
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement",
    rages: "5",
    rageDamage: "+4",
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Brutal Critical (3 dice)",
    rages: "6",
    rageDamage: "+4",
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Indomitable Might",
    rages: "6",
    rageDamage: "+4",
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement",
    rages: "6",
    rageDamage: "+4",
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Primal Champion",
    rages: "Unlimited",
    rageDamage: "+4",
  },
];
