import { ClassesTableData } from "../../models/ClassesTable";

export const bard: ClassesTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Spellcasting, Bardic Inspiration (d6)",
    cantripsKnown: "2",
    spellsKnown: "4",
    spellSlots: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features:
      "Jack of All Trades, Song of Rest (d6), Magical Inspiration (Optional)",
    cantripsKnown: "2",
    spellsKnown: "5",
    spellSlots: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Bard College, Expertise",
    cantripsKnown: "2",
    spellsKnown: "6",
    spellSlots: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement, Bardic Versatility (Optional)",
    cantripsKnown: "3",
    spellsKnown: "7",
    spellSlots: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Bardic Inspiration (d8), Font of Inspiration",
    cantripsKnown: "3",
    spellsKnown: "8",
    spellSlots: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Countercharm, Bard College feature",
    cantripsKnown: "3",
    spellsKnown: "9",
    spellSlots: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "3",
    spellsKnown: "10",
    spellSlots: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement, Bardic Versatility (Optional)",
    cantripsKnown: "3",
    spellsKnown: "11",
    spellSlots: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "Song of Rest (d8)",
    cantripsKnown: "3",
    spellsKnown: "12",
    spellSlots: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Bardic Inspiration (d10), Expertise, Magical Secrets",
    cantripsKnown: "4",
    spellsKnown: "14",
    spellSlots: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "-",
    cantripsKnown: "4",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement, Bardic Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "Song of Rest (d10)",
    cantripsKnown: "4",
    spellsKnown: "16",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Magical Secrets, Bard College feature",
    cantripsKnown: "4",
    spellsKnown: "18",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Bardic Inspiration (d12)",
    cantripsKnown: "4",
    spellsKnown: "19",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement, Bardic Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "19",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Song of Rest (d12)",
    cantripsKnown: "4",
    spellsKnown: "20",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Magical Secrets",
    cantripsKnown: "4",
    spellsKnown: "22",
    spellSlots: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement, Bardic Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "22",
    spellSlots: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Superior Inspiration",
    cantripsKnown: "4",
    spellsKnown: "22",
    spellSlots: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
