import { ClassTableData } from "../../models/ClassTableData";

export const bloodHunter: ClassTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Hunter's Bane, Blood Maledict",
    hemocraftDie: "1d4",
    bloodCursesKnown: "1",
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Fighting Style, Crimson Rite",
    hemocraftDie: "1d4",
    bloodCursesKnown: "1",
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Blood Hunter Order",
    hemocraftDie: "1d4",
    bloodCursesKnown: "1",
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement",
    hemocraftDie: "1d4",
    bloodCursesKnown: "1",
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Extra Attack",
    hemocraftDie: "1d6",
    bloodCursesKnown: "1",
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Brand of Castigation, Blood Maledict (2/rest)",
    hemocraftDie: "1d6",
    bloodCursesKnown: "2",
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "Order Feature, Crimson Rite Improvement",
    hemocraftDie: "1d6",
    bloodCursesKnown: "2",
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement",
    hemocraftDie: "1d6",
    bloodCursesKnown: "2",
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "Grim Psychometry",
    hemocraftDie: "1d6",
    bloodCursesKnown: "2",
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Dark Augmentation",
    hemocraftDie: "1d6",
    bloodCursesKnown: "3",
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Order Feature",
    hemocraftDie: "1d8",
    bloodCursesKnown: "3",
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement",
    hemocraftDie: "1d8",
    bloodCursesKnown: "3",
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "Brand of Tethering, Blood Maledict (3/rest)",
    hemocraftDie: "1d8",
    bloodCursesKnown: "3",
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Hardened Soul, Crimson Rite Improvement",
    hemocraftDie: "1d8",
    bloodCursesKnown: "4",
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Order Feature",
    hemocraftDie: "1d8",
    bloodCursesKnown: "4",
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement",
    hemocraftDie: "1d8",
    bloodCursesKnown: "4",
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Blood Maledict (4/rest)",
    hemocraftDie: "1d10",
    bloodCursesKnown: "4",
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Order Feature",
    hemocraftDie: "1d10",
    bloodCursesKnown: "5",
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement",
    hemocraftDie: "1d10",
    bloodCursesKnown: "5",
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Sanguine Mastery",
    hemocraftDie: "1d10",
    bloodCursesKnown: "5",
  },
];
