import { ClassTableData } from "../../models/ClassTableData";

export const cleric: ClassTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Spellcasting, Divine Domain",
    cantripsKnown: "3",
    spellSlots: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features:
      "Channel Divinity (x1), Divine Domain feature, Harness Divine Power (Optional)",
    cantripsKnown: "3",
    spellSlots: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "-",
    cantripsKnown: "3",
    spellSlots: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement, Cantrip Versatility (Optional)",
    cantripsKnown: "4",
    spellSlots: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Destroy Undead (CR 1/2)",
    cantripsKnown: "4",
    spellSlots: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Channel Divinity (x2), Divine Domain feature",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features:
      "Ability Score Improvement, Destroy Undead (CR 1), Divine Domain feature, Cantrip Versatility (Optional)",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "-",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Divine Intervention",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Destroy Undead (CR 2)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement, Cantrip Versatility (Optional)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Destroy Undead (CR 3)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement, Cantrip Versatility (Optional)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Destroy Undead (CR 4), Divine Domain feature",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Channel Divinity (x3)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement, Cantrip Versatility (Optional)",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Divine Intervention improvement",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
