import { ClassesTableData } from "../../models/ClassesTable";

export const monk: ClassesTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Unarmored Defense, Martial Arts",
    martialArts: "1d4",
    kiPoints: "-",
    unarmoredMovement: "-",
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Ki, Unarmored Movement, Dedicated Weapon (Optional)",
    martialArts: "1d4",
    kiPoints: "2",
    unarmoredMovement: "+10 ft.",
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features:
      "Monastic Tradition, Deflect Missiles, Ki-Fueled Attack (Optional)",
    martialArts: "1d4",
    kiPoints: "3",
    unarmoredMovement: "+10 ft.",
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features:
      "Ability Score Improvement, Slow Fall, Quickened Healing (Optional)",
    martialArts: "1d4",
    kiPoints: "4",
    unarmoredMovement: "+10 ft.",
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "Extra Attack, Stunning Strike, Focused Aim (Optional)",
    martialArts: "1d6",
    kiPoints: "5",
    unarmoredMovement: "+10 ft.",
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Ki-Empowered Strikes, Monastic Tradition feature",
    martialArts: "1d6",
    kiPoints: "6",
    unarmoredMovement: "+15 ft.",
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "Evasion, Stillness of Mind",
    martialArts: "1d6",
    kiPoints: "7",
    unarmoredMovement: "+15 ft.",
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement",
    martialArts: "1d6",
    kiPoints: "8",
    unarmoredMovement: "+15 ft.",
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "Unarmored Movement improvement",
    martialArts: "1d6",
    kiPoints: "9",
    unarmoredMovement: "+15 ft.",
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Purity of Body",
    martialArts: "1d6",
    kiPoints: "10",
    unarmoredMovement: "+20 ft.",
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Monastic Tradition feature",
    martialArts: "1d8",
    kiPoints: "11",
    unarmoredMovement: "+20 ft.",
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement",
    martialArts: "1d8",
    kiPoints: "12",
    unarmoredMovement: "+20 ft.",
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "Tongue of the Sun and Moon",
    martialArts: "1d8",
    kiPoints: "13",
    unarmoredMovement: "+20 ft.",
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Diamond Soul",
    martialArts: "1d8",
    kiPoints: "14",
    unarmoredMovement: "+25 ft.",
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Timeless Body",
    martialArts: "1d8",
    kiPoints: "15",
    unarmoredMovement: "+25 ft.",
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement",
    martialArts: "1d8",
    kiPoints: "16",
    unarmoredMovement: "+25 ft.",
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Monastic Tradition feature",
    martialArts: "1d10",
    kiPoints: "17",
    unarmoredMovement: "+25 ft.",
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Empty Body",
    martialArts: "1d10",
    kiPoints: "18",
    unarmoredMovement: "+30 ft.",
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement",
    martialArts: "1d10",
    kiPoints: "19",
    unarmoredMovement: "+30 ft.",
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Perfect Self",
    martialArts: "1d10",
    kiPoints: "20",
    unarmoredMovement: "+30 ft.",
  },
];
