import { ClassesTableData } from "../../models/ClassesTable";

export const sorcerer: ClassesTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    sorceryPoints: "-",
    features: "Spellcasting, Sorcerous Origin",
    cantripsKnown: "4",
    spellsKnown: "2",
    spellSlots: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    sorceryPoints: "2",
    features: "Font of Magic",
    cantripsKnown: "4",
    spellsKnown: "3",
    spellSlots: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    sorceryPoints: "3",
    features: "Metamagic",
    cantripsKnown: "4",
    spellsKnown: "4",
    spellSlots: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    sorceryPoints: "4",
    features: "Ability Score Improvement, Sorcerous Versatility (Optional)",
    cantripsKnown: "5",
    spellsKnown: "5",
    spellSlots: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    sorceryPoints: "5",
    features: "Magical Guidance (Optional)",
    cantripsKnown: "5",
    spellsKnown: "6",
    spellSlots: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    sorceryPoints: "6",
    features: "Sorcerous Origin feature",
    cantripsKnown: "5",
    spellsKnown: "7",
    spellSlots: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    sorceryPoints: "7",
    features: "-",
    cantripsKnown: "5",
    spellsKnown: "8",
    spellSlots: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    sorceryPoints: "8",
    features: "Ability Score Improvement, Sorcerous Versatility (Optional)",
    cantripsKnown: "5",
    spellsKnown: "9",
    spellSlots: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    sorceryPoints: "9",
    features: "-",
    cantripsKnown: "5",
    spellsKnown: "10",
    spellSlots: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    sorceryPoints: "10",
    features: "Metamagic",
    cantripsKnown: "6",
    spellsKnown: "11",
    spellSlots: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    sorceryPoints: "11",
    features: "-",
    cantripsKnown: "6",
    spellsKnown: "12",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    sorceryPoints: "12",
    features: "Ability Score Improvement, Sorcerous Versatility (Optional)",
    cantripsKnown: "6",
    spellsKnown: "12",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    sorceryPoints: "13",
    features: "-",
    cantripsKnown: "6",
    spellsKnown: "13",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    sorceryPoints: "14",
    features: "Sorcerous Origin feature",
    cantripsKnown: "6",
    spellsKnown: "13",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    sorceryPoints: "15",
    features: "-",
    cantripsKnown: "6",
    spellsKnown: "14",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    sorceryPoints: "16",
    features: "Ability Score Improvement, Sorcerous Versatility (Optional)",
    cantripsKnown: "6",
    spellsKnown: "14",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    sorceryPoints: "17",
    features: "Metamagic",
    cantripsKnown: "6",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    sorceryPoints: "18",
    features: "Sorcerous Origin feature",
    cantripsKnown: "6",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    sorceryPoints: "19",
    features: "Ability Score Improvement, Sorcerous Versatility (Optional)",
    cantripsKnown: "6",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    sorceryPoints: "20",
    features: "Sorcerous Restoration",
    cantripsKnown: "6",
    spellsKnown: "15",
    spellSlots: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
