import { ClassTableData } from "../../models/ClassTableData";

export const warlock: ClassTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Otherworldly Patron, Pact Magic",
    cantripsKnown: "2",
    spellsKnown: "2",
    warlockSpellSlots: "1",
    slotLevel: "1st",
    invocationsKnown: "-",
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Eldritch Invocations",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "1st",
    invocationsKnown: "2",
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Pact Boon",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "2nd",
    invocationsKnown: "2",
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement, Eldritch Versatility (Optional)",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "2nd",
    invocationsKnown: "2",
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "3rd",
    invocationsKnown: "3",
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Otherworldly Patron feature",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "3rd",
    invocationsKnown: "3",
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "4th",
    invocationsKnown: "4",
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement, Eldritch Versatility (Optional)",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "4th",
    invocationsKnown: "4",
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "-",
    cantripsKnown: "3",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "5th",
    invocationsKnown: "5",
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Otherworldly Patron feature",
    cantripsKnown: "4",
    spellsKnown: "2",
    warlockSpellSlots: "2",
    slotLevel: "5th",
    invocationsKnown: "5",
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "Mystic Arcanum (6th level)",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "5",
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement, Eldritch Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "6",
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "Mystic Arcanum (7th level)",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "6",
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Otherworldly Patron feature",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "6",
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "Mystic Arcanum (8th level)",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "7",
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement, Eldritch Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "3",
    warlockSpellSlots: "3",
    slotLevel: "5th",
    invocationsKnown: "7",
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "Mystic Arcanum (9th level)",
    cantripsKnown: "4",
    spellsKnown: "4",
    warlockSpellSlots: "4",
    slotLevel: "5th",
    invocationsKnown: "7",
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "-",
    cantripsKnown: "4",
    spellsKnown: "4",
    warlockSpellSlots: "4",
    slotLevel: "5th",
    invocationsKnown: "8",
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement, Eldritch Versatility (Optional)",
    cantripsKnown: "4",
    spellsKnown: "4",
    warlockSpellSlots: "4",
    slotLevel: "5th",
    invocationsKnown: "8",
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Eldritch Master",
    cantripsKnown: "4",
    spellsKnown: "4",
    warlockSpellSlots: "4",
    slotLevel: "5th",
    invocationsKnown: "8",
  },
];
