import { ClassesTableData } from "../../models/ClassesTable";

export const wizard: ClassesTableData[] = [
  {
    level: 1,
    proficiencyBonus: "+2",
    features: "Spellcasting, Arcane Recovery",
    cantripsKnown: "3",
    spellSlots: [2, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 2,
    proficiencyBonus: "+2",
    features: "Arcane Tradition",
    cantripsKnown: "3",
    spellSlots: [3, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 3,
    proficiencyBonus: "+2",
    features: "Cantrip Formulas (Optional)",
    cantripsKnown: "3",
    spellSlots: [4, 2, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 4,
    proficiencyBonus: "+2",
    features: "Ability Score Improvement",
    cantripsKnown: "4",
    spellSlots: [4, 3, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 5,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "4",
    spellSlots: [4, 3, 2, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 6,
    proficiencyBonus: "+3",
    features: "Arcane Tradition feature",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 0, 0, 0, 0, 0, 0],
  },
  {
    level: 7,
    proficiencyBonus: "+3",
    features: "-",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 1, 0, 0, 0, 0, 0],
  },
  {
    level: 8,
    proficiencyBonus: "+3",
    features: "Ability Score Improvement",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 2, 0, 0, 0, 0, 0],
  },
  {
    level: 9,
    proficiencyBonus: "+4",
    features: "-",
    cantripsKnown: "4",
    spellSlots: [4, 3, 3, 3, 1, 0, 0, 0, 0],
  },
  {
    level: 10,
    proficiencyBonus: "+4",
    features: "Arcane Tradition feature",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 0, 0, 0, 0],
  },
  {
    level: 11,
    proficiencyBonus: "+4",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 12,
    proficiencyBonus: "+4",
    features: "Ability Score Improvement",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 0, 0, 0],
  },
  {
    level: 13,
    proficiencyBonus: "+5",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 14,
    proficiencyBonus: "+5",
    features: "Arcane Tradition feature",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 0, 0],
  },
  {
    level: 15,
    proficiencyBonus: "+5",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 16,
    proficiencyBonus: "+5",
    features: "Ability Score Improvement",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 0],
  },
  {
    level: 17,
    proficiencyBonus: "+6",
    features: "-",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 2, 1, 1, 1, 1],
  },
  {
    level: 18,
    proficiencyBonus: "+6",
    features: "Spell Mastery",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 1, 1, 1, 1],
  },
  {
    level: 19,
    proficiencyBonus: "+6",
    features: "Ability Score Improvement",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 2, 1, 1, 1],
  },
  {
    level: 20,
    proficiencyBonus: "+6",
    features: "Signature Spells",
    cantripsKnown: "5",
    spellSlots: [4, 3, 3, 3, 3, 2, 2, 1, 1],
  },
];
