import { ItemsTableData } from "../../models/ItemsTable";

export const itemsData: ItemsTableData[] = [
  { name: "Armblade", type: "Weapon", isAttuned: true, source: "E:RLW" },
  { name: "Armor of Gleaming", type: "Armor", isAttuned: false, source: "XGE" },
  { name: "Band of Loyalty", type: "Ring", isAttuned: true, source: "WGTE" },
  {
    name: "Bead of Nourishment",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Bead of Refreshment",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Boots of False Tracks",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Bottle of Boundless Coffee",
    type: "Wondrous Item",
    isAttuned: false,
    source: "SCC",
  },
  {
    name: "Breathing Bubble",
    type: "Wondrous Item",
    isAttuned: false,
    source: "EGW",
  },
  {
    name: "Candle of the Deep",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  { name: "Cast-Off Armor", type: "Armor", isAttuned: false, source: "XGE" },
  {
    name: "Charlatan's Die",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  {
    name: "Chest of Preserving",
    type: "Wondrous Item",
    isAttuned: false,
    source: "WDMM",
  },
  {
    name: "Cleansing Stone",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Cloak of Billowing",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Cloak of Many Fashions",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Clockwork Amulet",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Clothes of Mending",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Coin of Delving",
    type: "Wondrous Item",
    isAttuned: false,
    source: "EGW",
  },
  {
    name: "Cuddly Strixhaven Mascot",
    type: "Wondrous Item",
    isAttuned: false,
    source: "SCC",
  },
  {
    name: "Dark Shard Amulet",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  {
    name: "Dread Helm",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Ear Horn of Hearing",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Earring of Message",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Enduring Spellbook",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  { name: "Ersatz Eye", type: "Wondrous Item", isAttuned: true, source: "XGE" },
  {
    name: "Everbright Lantern",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Feather Token",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Glamerweave",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Hat of Vermin",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Hat of Wizardry",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  {
    name: "Heward's Handy Spice Pouch",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Horn of Silent Alarm",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Illuminator's Tattoo",
    type: "Wondrous Item",
    isAttuned: true,
    source: "TCE",
  },
  {
    name: "Imbued Wood Focus",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Instrument of Illusions",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  {
    name: "Instrument of Scribing",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  { name: "Keycharm", type: "Wondrous Item", isAttuned: true, source: "E:RLW" },
  {
    name: "Lantern of Tracking",
    type: "Wondrous Item",
    isAttuned: false,
    source: "ID:RF",
  },
  {
    name: "Lock of Trickery",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Masque Charm",
    type: "Wondrous Item",
    isAttuned: false,
    source: "SCC",
  },
  {
    name: "Masquerade Tattoo",
    type: "Wondrous Item",
    isAttuned: true,
    source: "TCE",
  },
  {
    name: "Medal of Muscle",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of the Conch",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of the Horizonback",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of the Maze",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of the Meat Pie",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of the Wetlands",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Medal of Wit",
    type: "Wondrous Item",
    isAttuned: false,
    source: "CR:CN",
  },
  {
    name: "Mind Crystal",
    type: "Wondrous Item",
    isAttuned: false,
    source: "PBTSO",
  },
  {
    name: "Moodmark Paint",
    type: "Wondrous Item",
    isAttuned: false,
    source: "GGR",
  },
  {
    name: "Moon-Touched Sword",
    type: "Weapon",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Mystery Key",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Orb of Direction",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Orb of Gonging",
    type: "Wondrous Item",
    isAttuned: false,
    source: "WDMM",
  },
  {
    name: "Orb of Shielding",
    type: "Wondrous Item",
    isAttuned: true,
    source: "E:RLW",
  },
  {
    name: "Orb of Time",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Perfume of Bewitching",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Pipe of Remembrance",
    type: "Wondrous Item",
    isAttuned: false,
    source: "GoS",
  },
  {
    name: "Pipe of Smoke Monsters",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Pole of Angling",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Pole of Collapsing",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Pot of Awakening",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Potion of Climbing",
    type: "Potion",
    isAttuned: false,
    source: "DMG",
  },
  {
    name: "Potion of Healing",
    type: "Potion",
    isAttuned: false,
    source: "DMG",
  },
  {
    name: "Potion of Watchful Rest",
    type: "Potion",
    isAttuned: false,
    source: "WDMM",
  },
  {
    name: "Pressure Capsule",
    type: "Wondrous Item",
    isAttuned: false,
    source: "GoS",
  },
  {
    name: "Prosthetic Limb",
    type: "Wondrous Item",
    isAttuned: false,
    source: "TCE",
  },
  {
    name: "Rope of Mending",
    type: "Wondrous Item",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Ruby of the War Mage",
    type: "Wondrous Item",
    isAttuned: true,
    source: "XGE",
  },
  {
    name: "Scribe's Pen",
    type: "Wondrous Item",
    isAttuned: true,
    source: "E:RLW",
  },
  {
    name: "Sekolahian Worshipping Statuette",
    type: "Wondrous Item",
    isAttuned: false,
    source: "GoS",
  },
  {
    name: "Shield of Expression",
    type: "Armor",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Shiftweave",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  { name: "Smoldering Armor", type: "Armor", isAttuned: false, source: "XGE" },
  { name: "Spell Scroll", type: "Scroll", isAttuned: false, source: "DMG" },
  {
    name: "Spellshard",
    type: "Wondrous Item",
    isAttuned: false,
    source: "E:RLW",
  },
  {
    name: "Spellwrought Tattoo",
    type: "Wondrous Item",
    isAttuned: false,
    source: "TCE",
  },
  {
    name: "Staff of Adornment",
    type: "Staff",
    isAttuned: false,
    source: "XGE",
  },
  {
    name: "Staff of Birdcalls",
    type: "Staff",
    isAttuned: false,
    source: "XGE",
  },
];
