import { WeaponsTableData } from "../../models/WeaponsTable";

export const simpleMeleeWeaponsData: WeaponsTableData[] = [
  {
    name: "Club",
    price: "1 sp",
    damage: "1d4 bludgeoning",
    weight: "2 lb.",
    properties: "Light",
  },
  {
    name: "Dagger",
    price: "2 gp",
    damage: "1d4 piercing",
    weight: "1 lb.",
    properties: "Finesse, light, thrown (range 20/60)",
  },
  {
    name: "Greatclub",
    price: "2 sp",
    damage: "1d8 bludgeoning",
    weight: "10 lb.",
    properties: "Two-handed",
  },
  {
    name: "Handaxe",
    price: "5 gp",
    damage: "1d6 slashing",
    weight: "2 lb.",
    properties: "Light, thrown (range 20/60)",
  },
  {
    name: "Javelin",
    price: "5 sp",
    damage: "1d6 piercing",
    weight: "2 lb.",
    properties: "Thrown (range 30/120)",
  },
  {
    name: "Light hammer",
    price: "2 gp",
    damage: "1d4 bludgeoning",
    weight: "2 lb.",
    properties: "Light, thrown (range 20/60)",
  },
  {
    name: "Mace",
    price: "5 gp",
    damage: "1d6 bludgeoning",
    weight: "4 lb.",
    properties: "—",
  },
  {
    name: "Quarterstaff",
    price: "2 sp",
    damage: "1d6 bludgeoning",
    weight: "4 lb.",
    properties: "Versatile (1d8)",
  },
  {
    name: "Sickle",
    price: "1 gp",
    damage: "1d4 slashing",
    weight: "2 lb.",
    properties: "Light",
  },
  {
    name: "Spear",
    price: "1 gp",
    damage: "1d6 piercing",
    weight: "3 lb.",
    properties: "Thrown (range 20/60), versatile (1d8)",
  },
];

export const simpleRangedWeaponsData: WeaponsTableData[] = [
  {
    name: "Crossbow, light",
    price: "25 gp",
    damage: "1d8 piercing",
    weight: "5 lb.",
    properties: "Ammunition (range 80/320), loading, two-handed",
  },
  {
    name: "Dart",
    price: "5 cp",
    damage: "1d4 piercing",
    weight: "1/4 lb.",
    properties: "Finesse, thrown (range 20/60)",
  },
  {
    name: "Shortbow",
    price: "25 gp",
    damage: "1d6 piercing",
    weight: "2 lb.",
    properties: "Ammunition (range 80/320), two-handed",
  },
  {
    name: "Sling",
    price: "1 sp",
    damage: "1d4 bludgeoning",
    weight: "—",
    properties: "Ammunition (range 30/120)",
  },
];

export const martialMeleeWeaponsData: WeaponsTableData[] = [
  {
    name: "Battleaxe",
    price: "10 gp",
    damage: "1d8 slashing",
    weight: "4 lb.",
    properties: "Versatile (1d10)",
  },
  {
    name: "Flail",
    price: "10 gp",
    damage: "1d8 bludgeoning",
    weight: "2 lb.",
    properties: "—",
  },
  {
    name: "Glaive",
    price: "20 gp",
    damage: "1d10 slashing",
    weight: "6 lb.",
    properties: "Heavy, reach, two-handed",
  },
  {
    name: "Greataxe",
    price: "30 gp",
    damage: "1d12 slashing",
    weight: "7 lb.",
    properties: "Heavy, two-handed",
  },
  {
    name: "Greatsword",
    price: "50 gp",
    damage: "2d6 slashing",
    weight: "6 lb.",
    properties: "Heavy, two-handed",
  },
  {
    name: "Halberd",
    price: "20 gp",
    damage: "1d10 slashing",
    weight: "6 lb.",
    properties: "Heavy, reach, two-handed",
  },
  {
    name: "Lance",
    price: "10 gp",
    damage: "1d12 piercing",
    weight: "6 lb.",
    properties: "Reach, special",
  },
  {
    name: "Longsword",
    price: "15 gp",
    damage: "1d8 slashing",
    weight: "3 lb.",
    properties: "Versatile (1d10)",
  },
  {
    name: "Maul",
    price: "10 gp",
    damage: "2d6 bludgeoning",
    weight: "10 lb.",
    properties: "Heavy, two-handed",
  },
  {
    name: "Morningstar",
    price: "15 gp",
    damage: "1d8 piercing",
    weight: "4 lb.",
    properties: "—",
  },
  {
    name: "Pike",
    price: "5 gp",
    damage: "1d10 piercing",
    weight: "18 lb.",
    properties: "Heavy, reach, two-handed",
  },
  {
    name: "Rapier",
    price: "25 gp",
    damage: "1d8 piercing",
    weight: "2 lb.",
    properties: "Finesse",
  },
  {
    name: "Scimitar",
    price: "25 gp",
    damage: "1d6 slashing",
    weight: "3 lb.",
    properties: "Finesse, light",
  },
  {
    name: "Shortsword",
    price: "10 gp",
    damage: "1d6 piercing",
    weight: "2 lb.",
    properties: "Finesse, light",
  },
  {
    name: "Trident",
    price: "5 gp",
    damage: "1d6 piercing",
    weight: "4 lb.",
    properties: "Thrown (range 20/60), versatile (1d8)",
  },
  {
    name: "War pick",
    price: "5 gp",
    damage: "1d8 piercing",
    weight: "2 lb.",
    properties: "—",
  },
  {
    name: "Warhammer",
    price: "15 gp",
    damage: "1d8 bludgeoning",
    weight: "2 lb.",
    properties: "Versatile (1d10)",
  },
  {
    name: "Whip",
    price: "2 gp",
    damage: "1d4 slashing",
    weight: "3 lb.",
    properties: "Finesse, reach",
  },
];

export const martialRangedWeaponsData: WeaponsTableData[] = [
  {
    name: "Blowgun",
    price: "10 gp",
    damage: "1 piercing",
    weight: "1 lb.",
    properties: "Ammunition (range 25/100), loading",
  },
  {
    name: "Crossbow, hand",
    price: "75 gp",
    damage: "1d6 piercing",
    weight: "3 lb.",
    properties: "Ammunition (range 30/120), light, loading",
  },
  {
    name: "Crossbow, heavy",
    price: "50 gp",
    damage: "1d10 piercing",
    weight: "18 lb.",
    properties: "Ammunition (range 100/400), heavy, loading, two-handed",
  },
  {
    name: "Longbow",
    price: "50 gp",
    damage: "1d8 piercing",
    weight: "2 lb.",
    properties: "Ammunition (range 150/600), heavy, two-handed",
  },
  {
    name: "Net",
    price: "1 gp",
    damage: "—",
    weight: "3 lb.",
    properties: "Special, thrown (range 5/15)",
  },
];
